#
# Archivo de configuración para el cliente de LibreDTE
#
# Evita tener que estar pasando ciertos parámetros por la línea de comandos.
#
# En ambientes compartidos es obligatorio su uso, ya que así no se puede
# visualizar el parámetro --hash en la lista de procesos en ejecución.
#
# Para usar archivo de configuración copiar este archivo a config.yml y
# (usuarios en GNU/Linux) dejar con permisos 0600
#

# configuración para autenticación en LibreDTE
auth:
    url: https://libredte.cl
    hash:

# configuraciones para comandos
comandos:
